### ISSUE TITLE
Moving widgets does not work for new columns

### ISSUE THREAD

**Issue by ebtc** [sdorra/angular-dashboard-framework#103]
We experience some issues since updating to 0.8 of ADF (using Angular 1.3.15). Our issue sounds much like issue #60: you can move widgets within a column, but not to another. When moving a widget outside the containing column there is also no dropzone hint (as it used to be). Maybe it is an issue with Sortable (i have tried both 1.1.1 and 1.2.0 - same result)?

**Comment by sdorra** [comment]
Could you test agains the current master branch?
