### ISSUE TITLE
Adding new widget from a link in an existing widget

### ISSUE THREAD

**Issue by nwidodo** [sdorra/angular-dashboard-framework#105]
Hi,

I am trying to open another widget by clicking on a tooltip link from an existing widget. Is there a way to do this?

Thank you

**Comment by sdorra** [comment]
Sorry, that is current not possible.

**Comment by bteepell** [comment]
If anyone has thought about this please let me know.   I will be implementing something along these lines for a project I am doing.  When or if I get it working ill share.

**Comment by AjithVas** [comment]
Any luck on this?? I'm also looking for similar use case. Need to open a widget in a pop up on clicking on a link from another widget.
