### ISSUE TITLE
Template Parameter

### ISSUE THREAD

**Issue by eppak** [sdorra/angular-dashboard-framework#112]
It would be useful to parametrize the adfTemplatePath that now has a static value. If is parametrizable you can then redefine application aspect (localization etc).

.value("adfTemplatePath","../src/templates/")

What do you think?

**Comment by eppak** [comment]
I have fond that you can change by adding this:

.value('adfTemplatePath', '/templates/')

**Comment by eppak** [comment]
talked too early, if i place this parameter the application start to use the new template but editing buttons start to disappear. Any ideas?

**Comment by sdorra** [comment]
Do you have a sample?

**Comment by sdorra** [comment]
Closed because of inactivity.
