### ISSUE TITLE
Dynamic templateUrl for widget depend from config

### ISSUE THREAD

**Issue by nhatnguyen26** [sdorra/angular-dashboard-framework#115]
I want to make a widget with a generic action, however, I want to dynamically choose to render using a different html base on what I put into my config or other place, I already have different html that render my page in a different way, but I don't know how to dynamically get in rather than hardcoding the templateUrl to one file. Let me know if I am clear enough

**Comment by sdorra** [comment]
You could use a template with an dynamic include to workaround the problem. Please have a look at [this gist](https://gist.github.com/sdorra/33d24bd8e36f4d3011e0).
