### ISSUE TITLE
custom widget provided titleTemplateUrl is overwritten when widget is created dynamically

### ISSUE THREAD

**Issue by fuzzypete** [sdorra/angular-dashboard-framework#135]

**Comment by fuzzypete** [comment]
In widget.js in the preLink function. I think 

          if (!definition.titleTemplateUrl) {
            definition.titleTemplateUrl = adfTemplatePath + 'widget-title.html';
          }

should be 

          if (!definition.titleTemplateUrl) {
            definition.titleTemplateUrl = adfTemplatePath + 'widget-title.html';
            if (w.titleTemplateUrl) {
              definition.titleTemplateUrl = w.titleTemplateUrl;
            }
          }

**Comment by pgrzelka** [comment]
I agree with fuzzypete, apply necessary changes, please.

**Comment by sdorra** [comment]
Fixed by #139
