### ISSUE TITLE
ReferenceError: Sortable is not defined

### ISSUE THREAD

**Issue by b-ferreira** [sdorra/angular-dashboard-framework#136]
I'm facing a "ReferenceError: Sortable is not defined" every time my dashboard starts.

I've built my own release according instructions found on project's page.

I'm using angularJS v 1.3.11 and angular-dashboard-framework v 0.11.0.

Any suggestion ?

**Comment by sebastiandinu** [comment]
I've had this also,  make sure you load  Sortable library before adf. BTW if you're using RequireJS you may want to take a look at https://github.com/RubaXa/Sortable/issues/8

**Comment by b-ferreira** [comment]
That's my dependencies:

```html
<!-- Basic Lib JS files: jQuery + AngularJS + Pace -->
<script src="./libs/jquery/jquery-1.10.2.min.js"></script>
<script src="./libs/angular/angular.min.js"></script>
<script src="./libs/pace/pace.min.js"></script>

<!-- Chart Lib JS files: Highcharts + ExtendedHighcharts + ngHighcharts -->
<script src="./libs/highcharts/highstock.min.js"></script>
<script src="./libs/highcharts/highcharts-more.min.js"></script>
<script src="./libs/angular/highcharts/highcharts-ng.min.js"></script>

<!-- Dashboard Lib JS files: jQueryUI + ngJquerySortable + ngBootstrap + ngAngularDashboardFramework -->
<script src="./libs/jquery/jquery-ui-1.11.1.min.js"></script>
<script src="./libs/angular/jquery-sortable/sortable.min.js"></script>
<script src="./libs/angular/bootstrap/ui-bootstrap-tpls-0.11.2.min.js"></script>
<script src="./libs/angular/dashboard/angular-dashboard-framework.min.js"></script>
```

Should I change ```jquery-sortable/sortable.min.js``` to ```angular/ui-sortable```?

**Comment by sebastiandinu** [comment]
Yes, please do that

**Comment by b-ferreira** [comment]
Great! 

Problem solved.

Thank you for help me.

**Comment by b-ferreira** [comment]
Sorry, I did a mistake on my source code.

angular-ui-sortable didn't solved the problem. "ReferenceError: Sortable is not defined" persists.

Could we have another way to solve this problem?

Thanks for while.

**Comment by sdorra** [comment]
The angular-dashboard-framework uses [Sortable](https://github.com/RubaXa/Sortable) instead of [ui-sortable](https://github.com/angular-ui/ui-sortable) since version 0.8.0.

**Comment by b-ferreira** [comment]
That's it.

Problem solved with ```RubaXa/Sortable```.

Thanks again.
