### ISSUE TITLE
are more complex layouts possible?

### ISSUE THREAD

**Issue by imavroukakis** [sdorra/angular-dashboard-framework#33]
I'm trying to create the following layout in ADF

![layout](https://cloud.githubusercontent.com/assets/1764981/4525813/887beaee-4d58-11e4-8abf-03a05d57dc1e.png)

Is this at all achievable? I'm thinking it might only be possible with two dashboards on the page, one handling the left half and the other handling the right.

**Comment by sdorra** [comment]
Fixed by #52
