### ISSUE TITLE
trying to connect to grunt-connect-socket.io

### ISSUE THREAD

**Issue by zaibfridi** [sdorra/angular-dashboard-framework#51]
by following this link 
https://www.npmjs.com/package/grunt-connect-socket.io
i installed grunt.loadNpmTasks('grunt-connect-socket.io') plugin
i also make the socketio: true in gruntfile file...
now i have no idea how i use socket.io in my widget ....
i trying to make the location tracker widget in this framework but unable to use the socket.io 
i will be very thankfull if you gave me any reference ,any help  regarding to my problem.
thanks in advance

**Comment by sdorra** [comment]
I'm sorry, but i don't think that this is adf specific. This is more a question for the socket.io guys.
