### ISSUE TITLE
Have a generic JSON widget like freeboard.io

### ISSUE THREAD

**Issue by geshan** [sdorra/angular-dashboard-framework#53]
Freeboard.io has a generic JSON widget where you can select value from a JSON. Having something like that will help this project a lot.

**Comment by sdorra** [comment]
Could you describe this in more detail? What exactly does the widget?

**Comment by geshan** [comment]
You can get a value back from JSON and show it as a widget like if url returns a json with a javascript in this widget with a text area you could possibly write a java-script to return a string value that will be printed on the widget.

**Comment by sdorra** [comment]
I don't like the approach of executing a script, which was written by a user. This looks like a security risk.
