### ISSUE TITLE
Scope handling when compiling widgets

### ISSUE THREAD

**Issue by heikkilamarko** [sdorra/angular-dashboard-framework#55]
In `widget-content.js`, the function `compileWidget()` is invoked every time the widget is reloaded or its configuration is changed. It seems, that in each invocation, a new child scope is created but old scopes are never destroyed.

**Comment by sdorra** [comment]
You are right. I will try to fix it.

**Comment by sdorra** [comment]
The old scope will now be destroyed on reload.
