### ISSUE TITLE
Propose using Bootstrap glyphicons

### ISSUE THREAD

**Issue by Fationably-Late** [sdorra/angular-dashboard-framework#56]
How do you feel about using the glyphicons embedded in Bootstrap instead of importing a Font Awesome? I think this would make more sense to do this for streamlining since the library already depends on Bootstrap. There are icons that are a close match to the ones you're using currently.

**Comment by sdorra** [comment]
I think you are right switching to glyphicons make sense. We could remove the fontawesome dependency and it looks like angular-bootstraps depends on glyphicons too.
