### ISSUE TITLE
Changing dashboard still has widgets from previous dashboard in scope.

### ISSUE THREAD

**Issue by mittalsumeet** [sdorra/angular-dashboard-framework#57]
Hi
I have implemented auto refresh on a widget, which does polling to get data every 5 seconds. This widget is on dashboard "Sample 02". 

Now when I change dashboard to "Sample 01", the polling is still being called every 5 seconds, as the widget in Sample 02 is not destroyed when I change to Sample 01.

How can we remove all the previous widgets when I change dashboard from Sample 02 to Sample 01?

**Comment by sdorra** [comment]
This is not a bug of adf, this is the normal behavior of $timeout and $interval. You have to cancel them manually, if the scope is destroyed e.g.:

```javascript
var promise = $interval(function(){
  console.log('interval function called');
}, 1000);

$scope.$on('$destroy', function(){
  console.log('destroy widget scope and cancel interval');
  $interval.cancel(promise);
});
```
