### ISSUE TITLE
Open link inside widget and not as tab ? 

### ISSUE THREAD

**Issue by jcboncoin** [sdorra/angular-dashboard-framework#58]
Hi,
Is there a way to open a link inside a widget rather than in a new tab please?
I'm trying to embed an ionic app inside the widget actually.

Thank you!

**Comment by sdorra** [comment]
The only way i can think of at the moment, would be an iframe.

**Comment by sdorra** [comment]
Please have a look at the following widget:

- https://github.com/sdorra/adf-widget-iframe
