### ISSUE TITLE
Able to hide dashboard title and edit mode button

### ISSUE THREAD

**Issue by stanleyxu2005** [sdorra/angular-dashboard-framework#59]
In the sample application, each sample page has a title and an edit mode button on the right. It would be great, if we can remove title and the edit mode button. 
1. In some case, we might not want user have the ability to change the layout.
2. If title or the button or both are hidden, it'd be better to adjust the top-y position of the first column row.

**Comment by nunos7** [comment]
Hi,
To hide the edit button see issue #68.
