### ISSUE TITLE
D3.js implementation for table generation inside a markdown widget

### ISSUE THREAD

**Issue by Kirkos101** [sdorra/angular-dashboard-framework#61]
Hi,
I am trying to use the d3.js to create a table in a dashboard markdown widget. So far all my tests have failed. Is this implementation possible? If so, is there any example of how I can do this?
Thank you in advance.

**Comment by sdorra** [comment]
I've never used d3 tables in a widget. Could you post some code?

**Comment by Kirkos101** [comment]
Hi,
Here is the example code I am trying to make it work as a first step:

'use strict';
angular.module('fff.table.widgets', ['adf.provider', 'btford.markdown'])
  .value('githubApiUrl', 'https://api.github.com/repos/')
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('reservationTotals', {
        title: 'Reservation Totals',
        description: 'Reservation Totals widget',
        controller: 'reservationTotalsCtrl',
        templateUrl: 'scripts/widgets/ff_tables/ff_table.html',
		resolve: {
			read_data: function(FFFtradingService){
				return FFFtradingService.get();
			}
		},
        edit: {
          templateUrl: 'scripts/widgets/ff_tables/edit.html',
          reload: false
        }
      });
  })
  .service('SSStradingService', function($q, $http, githubApiUrl){
    return {
      get: function(/*path*/){
        var deferred = $q.defer();
		$.getJSON('9_Response.json', function(data) {
			if (data){
				deferred.resolve(data);
			}
		});
		
        return deferred.promise;
      }
    };
  })
  .controller('reservationTotalsCtrl', function($scope, config, read_data){
	
    var datapointsjson = {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    136.33, -31.5
                ]
            },
            "properties": {
                "regno": "R123456",
                "taxon": "genus1 species1",
                "sitecode": "",
                "nearestnamedplace": "FREELING ISLAND",
                "preciselocation": "south coast",
                "collection": "Herpetology"
            }
        }, {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    137.07, -36.23
                ]
            },
            "properties": {
                "regno": "R654185",
                "taxon": "genus2 species2",
                "sitecode": "",
                "nearestnamedplace": "Neptune Island",
                "preciselocation": "Middle of island",
                "collection": "Herpetology"
            }
        }, {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    142.0358, -38.7719
                ]
            },
            "properties": {
                "regno": "R6528445",
                "taxon": "genus3 species3",
                "sitecode": "TT02",
                "nearestnamedplace": "Woolongong",
                "preciselocation": "5 km N",
                "collection": "Herpetology"
            }
        }, {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    137.6914, -32.2789
                ]
            },
            "properties": {
                "regno": "R654987",
                "taxon": "genus4 species4",
                "sitecode": "IL0601",
                "nearestnamedplace": "Ballarat",
                "preciselocation": "5.3 KM E",
                "collection": "Herpetology"
            }
        }]
    };

	//console.log(datapointsjson);
    
    var headers = d3.keys(datapointsjson.features[0].properties);

    var thedatatable = d3.select("#propertiestable")
        .append("table")
        .attr("class", "datatable");

    var header = thedatatable.selectAll("th")
        .data(headers)
        .enter()
        .append("th")
        .text(function (d) {
            return d;
        });

    var tr = thedatatable.selectAll("tr")
        .data(d3.values(datapointsjson.features))
        .enter()
        .append("tr");

    var td = tr.selectAll("td")
        .data(function(row) {
            return headers.map(function(d) { console.log(row.properties)
                return {column: d, value: row.properties[d]};
            });
        })
        .enter()
        .append("td")
        .text(function (d) {
            return d.value;
        });
	
	config.content = "<div id='propertiestable' style='margin: 30px;'></div>";

  });

**Comment by sdorra** [comment]
Tow problems, the first on is the $.getJSON. This method comes from jQuery and should not be used in an angular application, please use [$http](https://code.angularjs.org/1.2.28/docs/api/ng/service/$http) to retrieve the data. The next problem is the way you are trying to create the content of the widget, i think you have to create a directive for this.

**Comment by sdorra** [comment]
The following example should work:

**table.js**
```java
'use strict';

angular.module('adf.widget.table', ['adf.provider'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('table', {
        title: 'table Title',
        description: 'Description of table',
        controller: 'tableController',
        templateUrl: '{widgetsPath}/table/src/view.html',
        resolve: {
          tabledata: function(tableService){
            return tableService.get();
          }
        }
      });
  })
  .service('tableService', function($q, $http){
    return {
      get: function(){
        var deferred = $q.defer();
        $http.get('9_Response.json')
          .success(function(data){
            deferred.resolve(data.data);
          })
          .error(function(){
            deferred.reject();
          });
        return deferred.promise;
      }
    };
  })
  .controller('tableController', function($scope, tabledata){
    $scope.data = tabledata;
  })
  .directive('d3Table', function(){
    return {
      restrict: 'EA',
      scope: {
        data: '='
      },
      link: function(scope, element, attrs) {
        var datapointsjson = scope.data;

        var headers = d3.keys(datapointsjson.features[0].properties);

        var thedatatable = d3.select(element[0])
               .append("table")
               .attr("class", "datatable");

        var header = thedatatable.selectAll("th")
             .data(headers)
             .enter()
             .append("th")
             .text(function (d) {
                 return d;
             });

         var tr = thedatatable.selectAll("tr")
             .data(d3.values(datapointsjson.features))
             .enter()
             .append("tr");

         var td = tr.selectAll("td")
             .data(function(row) {
                 return headers.map(function(d) { console.log(row.properties)
                     return {column: d, value: row.properties[d]};
                 });
             })
             .enter()
             .append("td")
             .text(function (d) {
                 return d.value;
             });
      }
    };
  });
```

**view.html**
```html
<div>
  <h1>Table data</h1>
  <d3-table data="data"></d3-table>
</div>
```

**Comment by Kirkos101** [comment]
Thank you for your answer. 
However still it doesn't work. I used the above code only with a small change for templateURL path (`scripts/widgets/tables/view.html` as the `{widgetsPath}/` is not recgnizable)
I also created the view.html as above and stored according to templateURL path.
In sample.js I added the `'adf.widget.table'` (modules declaration)
Modified sample-04.js as follows
```
...
                 "columns": [
                    {
                      "styleClass": "col-md-12",
                      "widgets": [
                        {
                          "type": "table",
                          "title": "Reservation Totals"
                        }
...
```
Finally, I can see only the header (Table data) from header of view.html.
What am I doing wrong?
Once again, thank you in advance for your help.

**Comment by Kirkos101** [comment]
(Sorry, I repeat my last comment as I closed the issue by mistake)
Thank you for your answer. 
However still it doesn't work. I used the above code only with a small change for templateURL path (`scripts/widgets/tables/view.html` as the `{widgetsPath}/` is not recgnizable)
I also created the view.html as above and stored according to templateURL path.
In sample.js I added the `'adf.widget.table'` (modules declaration)
Modified sample-04.js as follows
```
...
                 "columns": [
                    {
                      "styleClass": "col-md-12",
                      "widgets": [
                        {
                          "type": "table",
                          "title": "Reservation Totals"
                        }
...
```
Finally, I can see only the header (Table data) from header of view.html.
What am I doing wrong?
Once again, thank you in advance for your help.

**Comment by sdorra** [comment]
Do you have included the script file in the index.html? Could you post the output of you browser console?

**Comment by Kirkos101** [comment]
Yes, I did.
Also find attached the screenshot.
![2015-02-17_232738](https://cloud.githubusercontent.com/assets/10725027/6237596/f1041e0c-b6fc-11e4-91f1-c6f200edc62e.jpg)

**Comment by sdorra** [comment]
It looks like the widget is not able to load your json file:

```text
 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Please check the network tab of the developer tools in your browser.

**Comment by Kirkos101** [comment]
I checked and I removed `pivot.js` I load. Now the Console Output is
```
TypeError: Cannot read property '0' of undefined
    at link (http://localhost:9001/sample/scripts/widgets/3s_tables/table.js:45:54)
    at http://localhost:9001/sample/components/angular/angular.js:7035:44
    at nodeLinkFn (http://localhost:9001/sample/components/angular/angular.js:6633:13)
    at compositeLinkFn (http://localhost:9001/sample/components/angular/angular.js:6028:13)
    at compositeLinkFn (http://localhost:9001/sample/components/angular/angular.js:6031:13)
    at publicLinkFn (http://localhost:9001/sample/components/angular/angular.js:5923:30)
    at $q.all.then.msg (http://localhost:9001/src/scripts/widget-content.js:100:38)
    at deferred.promise.then.wrappedCallback (http://localhost:9001/sample/components/angular/angular.js:11446:81)
    at http://localhost:9001/sample/components/angular/angular.js:11532:26
    at Scope.$get.Scope.$eval (http://localhost:9001/sample/components/angular/angular.js:12556:28) <d3-table data="data" class="ng-isolate-scope">
```
In the Network tab I see that json file is loaded.
According to the above console output, It seems there is a problem in line 45:54 of `table.js`
I removed `var headers' and `var header` (the variables corresponding to these lines) and I get no errors in the console. However I still get no result, only the widget now appears bigger.

**Comment by Kirkos101** [comment]
Finally, it works!
Thank you very much for your help!
