### ISSUE TITLE
ng-grid.js - loading file for use inside a widget

### ISSUE THREAD

**Issue by Kirkos101** [sdorra/angular-dashboard-framework#64]
Hi,
I am trying to use `ng-grid.js` for data table generation inside a widget.
By loading the `ng-grid.js` into `index.html` I am getting the following error in the console:
`Uncaught ReferenceError: angular is not defined`
I 've tried miscellaneous positions inside `index.html` to call the file but the result remains the same.
Any ideas?
Thank you in advance.

**Comment by Kirkos101** [comment]
Finally I found the correct position into `index.html` to call the file (I hope).
Now my problem is that angular does not recognize the variable that returns the data (the `alphadata` variable in this case) and I get the following error:
`Error: [$injector:unpr] Unknown provider: alphadataProvider <- alphadata`
My code is as follows:
```
'use strict';

angular.module('alphabeta.table.widgets', ['adf.provider', 'btford.markdown', 'ngGrid'])
  .value('githubApiUrl', 'https://api.github.com/repos/')
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('reservationTotals', {
        title: 'Reservation Totals',
        description: 'Reservation Totals widget',
        controller: 'reservationTotalsCtrl',
        templateUrl: 'scripts/widgets/alphabeta/alphabeta.html',
		resolve: {
			alphadata: function(SSStradingService){
				return SSStradingService.get();
			}
		},
        edit: {
          templateUrl: 'scripts/widgets/alphabeta/edit.html',
          reload: false
        }
      });
  })
  .service('SSStradingService', function($q, $http, githubApiUrl){
    return {
      get: function(){
        var deferred = $q.defer();
        $http.get('9_Response.json')
          .success(function(data){
            deferred.resolve(data);
          })
          .error(function(){
            deferred.reject();
          });
        return deferred.promise;
      }
    };
  })
  .controller('reservationTotalsCtrl', function($scope, alphadata){
	
	var tabledata = [];
	
	var i, n;
	var ycount=0, yexist=0;
	var numf;
	for(i=0;i<alphadata.length;i++){
		yexist=0;
		for(n=0;n<ycount;n++){
			if (alphadata[i].stYear == tabledata[n].Year && alphadata[i].market == tabledata[n].Market) {
				tabledata[n].Sales += alphadata[i].totSale;
				tabledata[n].Sales = parseFloat(Math.round(tabledata[n].Sales * 100) / 100);
				yexist++;
				break;
			} 
		}
		if (!yexist) {
			numf = alphadata[i].totSale;
			tabledata.push({
					Market: alphadata[i].market,
					Year: alphadata[i].stYear,
					Sales: parseFloat(Math.round(numf * 100) / 100),
					CustomerName: alphadata[i].custName
			});
			ycount++;	
		}			
	}
	
	$scope.data = tabledata;
	
	$scope.gridOptions = {
        data: 'data',
        enablePinning: true,
        columnDefs: [{ field: "Market", width: 60, pinned: true },
                    { field: "Year", width: 60 },
                    { field: "Sales", width: 60 },
                    { field: "CustomerName", width: 60 }]
    };
	
	console.log($scope.data);

  });

  ```
The alphabeta.html is:
```
<div>
  <h1>Table data</h1>
      <div ng-controller="reservationTotalsCtrl">
        <div class="gridStyle" ng-grid="gridOptions"></div>
    </div>
 </div>
```
Any ideas?

**Comment by sdorra** [comment]
The code looks good for me. Do you have multiple modules, with the same name ('alphabeta.table.widgets')?

**Comment by sdorra** [comment]
was the ``` $http.get('9_Response.json') ``` successful?

**Comment by Kirkos101** [comment]
It seems it is ok. By using `console.log(alphadata);` at the end of controller code I am getting the correct result. I just don't understand why ng-grid consider this as unknown provider and produces error.

**Comment by Kirkos101** [comment]
I do not have other module with the same name. I checked.

**Comment by sdorra** [comment]
You have defined the controller twice. The first time with the widget registration:

```javascript
controller: 'reservationTotalsCtrl',
```

adf will use this controller to render the template. You don't have to use the ng-controller directive in your view (the second use):

```html
<div ng-controller="reservationTotalsCtrl">
```

Just remove the directive from your view. Then your view should look like the following and the error should be fixed:

```html
<div>
  <h1>Table data</h1>
  <div class="gridStyle" ng-grid="gridOptions"></div>
</div>
```

By the way you should remove the githubApi and the markdown stuff from your widget, because it is not used.
