### ISSUE TITLE
Collapsible don't work?

### ISSUE THREAD

**Issue by nunos7** [sdorra/angular-dashboard-framework#65]
Hi,
I'm installing the release version 0.6.1, when load the sample 2, who has the collapsible option to true, the widget don't show the collapsible option...

NS

**Comment by nunos7** [comment]
Hi, in widget.js the scope is collapsible: '=', i think the correct way is collapsible: '@' ?

NS

**Comment by sdorra** [comment]
Yes, you are right.

**Comment by sdorra** [comment]
Sorry, but this does not fix the problem. Now the collapsible mode is always on, i will try to fix it.

**Comment by sdorra** [comment]
Ok, now it is really fixed.
