### ISSUE TITLE
Widgets with defined width

### ISSUE THREAD

**Issue by zdgadd** [sdorra/angular-dashboard-framework#66]
As is, widgets take the full width of the column they've been added to.

Does anyone know if it's possible to have widgets define their own width? So that layouts like below are possible:

![layout](https://cloud.githubusercontent.com/assets/6838015/6375285/f9623612-bd0d-11e4-8e10-e1fcbe875f8f.png)

Looking at the widget template I can't see a semantic way to achieve this, but if anyone's faced this or has suggestions your input would be greatly appreciated! I must confess, I'm new to bootstrap, but I'm coming from foundation so I understand the basics, so I may be missing an easy win.

**Comment by sdorra** [comment]
No, widgets can not define their own width. But your picture looks like the following structure:

```javascript
  dashboardProvider
    .structure('6-6 12 4-8', {
      rows: [{
        columns: [{
          styleClass: "col-md-6"
        }, {
          styleClass: "col-md-6"
        }]
      },{
        columns: [{
          styleClass: "col-md-12"
        }]
      },{
        columns: [{
          styleClass: "col-md-4"
        }, {
          styleClass: "col-md-8"
        }]
      }]
    });
```

The dashboard (enabled editMode), will look like the following:

![dashboard](https://cloud.githubusercontent.com/assets/493333/6380285/d50393c6-bd38-11e4-8f24-02bffb1696d4.png)

**Comment by zdgadd** [comment]
Ok thanks. The sample layout unfortunately doesn't suit what I need, as it simple fixes the columns/rows and scales the widgets in them. I need the widgets to be fixed width and for them to wrap onto new rows where appropriate.

I will see if I can tweak this use case into existence. Thanks all the same though.
