### ISSUE TITLE
Reload data by user action

### ISSUE THREAD

**Issue by bgruenefeld** [sdorra/angular-dashboard-framework#67]
I've created a widget which displays time series data in a chart.
The user can select defined time rages (e.g. Day, week, Month), data loaded from the server and the chart data will be refreshed -> works already.

Is there a possibility to show the loading bar during data loading?

**Comment by sdorra** [comment]
You could fire the widgetReload event from your widget, but this will do a full reload of the widget.

**Comment by bgruenefeld** [comment]
thx, now it works.
complete reload of the widget is currently ok for me.
