### ISSUE TITLE
Option to show/ hide edit mode

### ISSUE THREAD

**Issue by nunos7** [sdorra/angular-dashboard-framework#68]
Hi Sebastian,
Is it possible to have an option to show/ hide the edit option?
In my testing page i've created a variable allowEdit = false and then i've setted her to the model object. In dashboard.html, i've setted ng-if="model.allowEdit" to the span DOM object. 
This works, but i don't know if it's the more elegant solution?

Thanks,
NS

**Comment by sdorra** [comment]
I think a better way is to use an attribute for the adf-dashboard directive, this would be analog to the collapsible option.

**Comment by nunos7** [comment]
Hi, 
A good improvement was to put both the "collapsible" and "allowEdit" individual by widget and/ or global by dashboard.
The global option in dashboard should be mandatory on the individual option of the widget.

Thanks,
NS

**Comment by sdorra** [comment]
You can now use the editable attribute on the adf-dashboard directive for example:

```html
<adf-dashboard editable="false" ...
```

Or with expression:

```html
<adf-dashboard editable="{{scopeVar}}" ...
```

@nunos7 each widget can control if it is editable or not, by adding the edit property. If the edit property is missing, only the title can be changed. I think the collapsible option for individual widgets, does not make much sense.

**Comment by nunos7** [comment]
You rock.

NS

**Comment by RajaGowthu** [comment]
Could someone help me how to hide settings(cog) icon for specific widget in my dashboard.

Thanks in advance
