### ISSUE TITLE
Widget Config $scope updates do not show up

### ISSUE THREAD

**Issue by floridait** [sdorra/angular-dashboard-framework#71]
The problem I have is when I configure a widget, I update the $scope in the edit controller with some data based on a select box value with a ng-change.

Widget Config
then
Select box choose value with ng-change fire function in edit controller 
then 
update $scope.blah which is used for values in another select box under the first select box

The $scope changes do not propagate into the current config modal template.

When I do a console.log on the $scope in the edit controller I see the changes.

I believe the problem exists in the widget-content.js because when the templates get loaded dynamically the scope does not update.

Do you have any information that will help me see the scope changes that are happening in the edit controller in the background in the current template in the config modal?

**Comment by sdorra** [comment]
Could you post a sample?

**Comment by floridait** [comment]
The sample would be way to long. In the widget-content.js in the compileWidget function seems to be the problem.

What I am trying to do is simple:

1. I have a widget that I am trying to configure by clicking on configure.

2. In the configure controller I have a function $scope.accountChanged that is being called from the template on an ng-change="accountChanged()" which is in a select element with ng-options.

3. Back in the configure controller in the accountChanged() function I am reading out of the scope which account has been selected and then making a call to get data which will be loaded into $scope.campaigns which is the $scope variable of another select element.

4. the second select element should now update itself with the new data which came from accountChanged() but is not updating.

This works outside of configuration modals. My assumption is that it has to do with the way $scope is handled in the compileWidget function inside the widget-content.js

I want to dynamically load data into select boxes based on the select box above it. The normal 2 way binding of $scope variables does not seem to work in configuration modals for the widgets.

**Comment by floridait** [comment]
This can easily be tested with using ng-options with ng-change="someFunction()"...

In the config template create a tag with {{updates}} which by default is an empty array configured in the edit controller with $scope.updates = [].

in someFunction() when it is called by the change of the select boxes ng-change fill the updates array with some data $scope.updates.push({blah:'blah'}). If the $scope would update correctly you should now see the {{updates}} variable change in your tag in the config template. It does not.

**Comment by sdorra** [comment]
I can't reproduce this issue. Here is my test widget:

awesome.js:

```javascript
'use strict';

angular.module('adf.widget.awesome', ['adf.provider'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('awesome', {
        title: 'My awesome widget',
        description: 'This my awesome widget, to test issue #71',
        templateUrl: '{widgetsPath}/awesome/src/view.html',
        edit: {
          templateUrl: '{widgetsPath}/awesome/src/edit.html',
          controller: 'AwesomeEditController'
        }
      });
  })
  .controller("AwesomeEditController", function($scope){

    $scope.selections = [];

    $scope.options = [
      { label: 'one', value: 1 },
      { label: 'two', value: 2 },
      { label: 'three', value: 3 },
      { label: 'four', value: 4 }
    ];

    $scope.storeSelection = function(){
      var sel = $scope.selected;
      if ($scope.selections.indexOf(sel) < 0){
        $scope.selections.push(sel);
      }
    }

  });
```
edit.html:

```html
<form role="form">
  <select ng-model="selected"
          ng-options="opt as opt.label for opt in options"
          ng-change="storeSelection()">
  </select>
  <h4>Selected</h4>
  <ul>
    <li ng-repeat="selection in selections">
      {{selection.label}}
    </li>
  </ul>
</form>
```

**Comment by floridait** [comment]
I ended up using the parent scope and all my worries were gone. I probably did not understand scopes that well but this bug can be closed.
