### ISSUE TITLE
Cannot pass a variable from directive to controller in a markdown widget

### ISSUE THREAD

**Issue by Kirkos101** [sdorra/angular-dashboard-framework#72]
I am trying to pass a variable from directive to controller in a markdown widget. Normally, the following example should work:

my controller:
```
    .controller('reservationTotalsCtrl', function($scope, read_data){

	$scope.foo = 'Hello!';

	$scope.data = read_data;

	//Something...
	.
        .
        .
	})
```
the directive

```.
.directive('d3Table', function(){ 
    return {
      restrict: 'EA',
      scope: {
        data: '=',
	isolatedAttributeFoo: '=attributeFoo'
      },
      link: function(scope, element, attrs) {
	  
	  //Something
	  .
	  .
	  .
	  });
```
the view.html

```
<input ng-model="foo">
  <d3-table data="data" attribute-foo="foo">
  <input ng-model="isolatedAttributeFoo">
  </d3-table>
```
What I am trying to achieve, is to transfer the content of the input box `foo` to `isolatedAttributeFoo` 
input box. The above example (based on http://jsfiddle.net/maxisam/QrCXh/) would have to work but it doesn't
Are there any ideas what might be wrong?

Thank you in advance

**Comment by sdorra** [comment]
This is not adf related. Please ask this question in an angular forum or an stackoverflow.
