### ISSUE TITLE
"Cannot read property 'unshift' of undefined" error

### ISSUE THREAD

**Issue by alcfeoh** [sdorra/angular-dashboard-framework#73]
"Cannot read property 'unshift' of undefined at Scope.controller.f.addWidgetDialog.b.addWidget "

It's an error I get when I try to add a new widget to my dashboard. Please note that the default dashboard is empty so it has no model. It seems that the widget list is not initialized to an empty list in that case.

**Comment by sdorra** [comment]
Is model empty or undefined? Do you have widgets defined?

**Comment by alcfeoh** [comment]
I do not use any model, which means that I don't add the model attribute to the adf-dashboard element

**Comment by sdorra** [comment]
Ok, i see it seems not to work. I will try to fix it.

**Comment by sdorra** [comment]
Could you try with a fresh copy of the master branch?

**Comment by alcfeoh** [comment]
Thanks, it works now.

Alain Chautard

**Comment by belveryin** [comment]
I've just came across this problem too. I've started to play around with this dashboard and I am using bower to add it to my project. Is this fix going to be available in the bower package? The only way to get this fix is via git clone master?
