### ISSUE TITLE
How to transfer variable values among widgets

### ISSUE THREAD

**Issue by Kirkos101** [sdorra/angular-dashboard-framework#74]
Hi,

Thank you for your answers to my previous questions, was very helpful.
Currently, I am trying to transfer variable values among widgets. How can I do this?
Is it possible to define global variables?
I have used already `.service ()` to read and transfer external data among widgets.
But how can I transfer values of variables or data generated by a widget itself, in other widgets?

Also, how can I reload a widget in order to refresh the appeared data?

Thank you in advance

**Comment by lukee910** [comment]
As far as I know there are no 'Global Variables', except for the angular.config.

You could use `$rootScope.$broadcast` with arguments. For example:
```
// Widget 1
$rootScope.$broadcast('msgWidget2', { data: 'Hello' });
```
```
// Widget 2
$scope.$on('msgWidget2', function(event, args){
    $scope.data = args.data;
});
```

**Comment by sdorra** [comment]
I think using services for communication is a much better approach, then sending events over the root scope. Please have a look at this [gist](https://gist.github.com/sdorra/33d24bd8e36f4d3011e0).

**Comment by imadie** [comment]
could you explain a bit on the gist?
