### ISSUE TITLE
Cannot assign to read only property '$methodName' of false Use --force to continue

### ISSUE THREAD

**Issue by harshmer** [sdorra/angular-dashboard-framework#75]
Hi @sdorra :

Have come across a new issue. The link to this issue is https://github.com/olov/ng-annotate/issues/139

Its about ng-annotate.
The solution mentioned in it is if ng-annotate is upgraded to the new version this error would be gone.

Can it be possible to upgrade the ng-annotate in the framework?

Thanks Sebastian.

Best Regards,
Harsh

**Comment by sdorra** [comment]
Could you test again?

**Comment by harshmer** [comment]
Hi @sdorra 

Thanks a mill. No warnings now. Builds successfully.

Best Regards,
Harsh
