### ISSUE TITLE
Automatic Reload

### ISSUE THREAD

**Issue by eppak** [sdorra/angular-dashboard-framework#76]
Hello,
if i create a gauge widget and i want to refresh it automatically, how force update? There is a way to bind ad "external" action to an internal content?

Thanks in advance.

**Comment by eppak** [comment]
I found a solution in the widget controller. I use the randomstring widget for example:

...
  .controller('randommsgCtrl', function($scope, randommsgService, $interval){
                $scope.msg = randommsgService.get();
		$interval(function() { $scope.msg = randommsgService.get(); }, 1000);	
  });

Is a clean solution?

**Comment by sdorra** [comment]
Using $interval is fine, but you have to cancel the $interval on scope destroy, e.g.:

```javascript
var promise = $interval(function() { 
  $scope.msg = randommsgService.get(); 
}, 1000);

// cancel interval on scope destroy
$scope.$on('$destroy', function(){
  $interval.cancel(promise);
});
```

Please have a look at the [clock widget](https://github.com/sdorra/adf-widget-clock/blob/master/src/clock.js) for a real live example.
