### ISSUE TITLE
Using a controller to manage the edit panel

### ISSUE THREAD

**Issue by Silverspur** [sdorra/angular-dashboard-framework#77]
Hi,
I'm really not an expert in AngularJS, but from what I understood of the code, the edit panel is managed by a controller included in the adf module so that `config` is directly available. Is it possible somehow to add custom behaviour in this controller?
For instance, assume I have a select field and a text field in my edit panel, and I want the select field to have "Other" selected as soon as the user types some text in the field.
I of course know how to do that in a standard controller, but I'm unsure of how such a custom controller should merge with the one included in the adf module (if that is even possible).

**Comment by sdorra** [comment]
You can specify a controller for the edit dialog during the registration e.g.:

```javascript
angular.module('mywidget', ['adf.provider'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('mywidget', {
        title: 'My Widget',
        description: 'My awesome widget',
        templateUrl: 'mywidget/src/view.html',
        edit: {
          templateUrl: 'mywidget/src/edit.html',
          reload: false,
          controller: 'MyEditController'
        }
      });
  }).controller('MyEditController', function($scope, config){
    // do something
  });
```

Please have a look at the [linklist widget](https://github.com/sdorra/adf-widget-linklist/blob/master/src/linklist.js) for a real world example.

**Comment by Silverspur** [comment]
Perfect, thanks. I had missed that.
