### ISSUE TITLE
Multiple directives [adfDashboardColumn, uiSortable] asking for new/isolated scope

### ISSUE THREAD

**Issue by mingledj** [sdorra/angular-dashboard-framework#78]
I am getting this error whenever I try to load the Dashboard. The dashboard contents does not load, just the title and the edit button. I have found that removing sortable-options="sortableOptions" from a few places in angular-dashboard-framework.min.js solves this issue, but removes the ability to rearrange the widgets which is a feature I need. I will continue to look into this myself, any assistance on this issue would be greatly appreciated.

Thank you.

**Comment by sdorra** [comment]
I think this message is thrown, if jquery-ui is not loaded. Do you have included all dependencies (jquery, jquery-ui, angular, angular-bootstrap and angular-ui-sortable). Did you see any 404 messages during load of your index.html?

**Comment by mingledj** [comment]
I did not see any 404 messages, the page loads fine with the exception of the dashboard content not being present. I just checked, I am including all of those dependencies.

**Comment by sdorra** [comment]
How did you installed the dashboard? Checkout, bower and which version do you use? And which angular version do you use?

**Comment by mingledj** [comment]
I am fairly new to web development, I am not familiar with Bower (will reinstall dashboard using it now) I just got the files from GitHub. I am currently using AngularJS v1.3.8.

**Comment by mingledj** [comment]
I updated my Angular to v1.3.15 and installed the Dashboard on my machine using Bower. I copied the angular-dashboard-framework.min.js and css from the dist directory into my Visual Studio project, I am still having the same issue though. I feel like I might be missing a step somewhere.

**Comment by sdorra** [comment]
If you have included all required components, your index should look like the following:

```html
<script type="text/javascript" src="components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="components/jquery-ui/ui/minified/core.min.js"></script>
<script type="text/javascript" src="components/jquery-ui/ui/minified/widget.min.js"></script>
<script type="text/javascript" src="components/jquery-ui/ui/minified/mouse.min.js"></script>
<script type="text/javascript" src="components/jquery-ui/ui/minified/sortable.min.js"></script>
<script type="text/javascript" src="components/angular/angular.min.js"></script>
<script type="text/javascript" src="components/angular-ui-sortable/sortable.min.js"></script>
<script type="text/javascript" src="components/angular-route/angular-route.min.js"></script>
<script type="text/javascript" src="components/angular-bootstrap/ui-bootstrap.min.js"></script>
<script type="text/javascript" src="components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
<script type="text/javascript" src="components/angular-dashboard-framework/dist/angular-dashboard-framework.min.js"></script>
```

Could you post your index.html? Why you copy the files to your visual studio project? I believe you can integrate bower components directly in your project (http://www.asp.net/vnext/overview/aspnet-vnext/grunt-and-bower-in-visual-studio-2015). For a real world example with angular 1.3 you can look at the [adf-dynamic-example](https://github.com/sdorra/adf-dynamic-example).

**Comment by ebtc** [comment]
We have a similar issue after switching to jspm as package manager. I do also believe that it has to do with dependencies (maybe conflict). Would it be possible to include a jspm directive in the package.json (like bootstrap did): https://github.com/twbs/bootstrap/blob/master/package.json#L77

**Comment by mingledj** [comment]
I am actually working in a Single Page Application. I am referencing the scripts using a C# BundleCollection. My collection is as follows:
                        "~/Scripts/json2.min.js",
                        "~/Scripts/jquery-2.1.1.min.js",
                        "~/Scripts/modernizr-2.8.3.js",
                        "~/Scripts/jquery-ui-1.11.2.min.js",
                        "~/Scripts/bootstrap.min.js",
                        "~/Scripts/moment-with-locales.min.js",
                        "~/Scripts/jquery.blockUI.js",
                        "~/Scripts/toastr.min.js",
                        "~/Scripts/others/spinjs/spin.js",
                        "~/Scripts/others/spinjs/jquery.spin.js",
                        "~/Scripts/angular.min.js",
                        "~/Scripts/angular-animate.min.js",
                        "~/Scripts/angular-sanitize.min.js",
                        "~/Scripts/angular-route.min.js",
                        "~/Scripts/angular-ui-router.min.js",
                        "~/Scripts/angular-ui/sortable.js",
                        "~/Scripts/angular-ui/ui-bootstrap.min.js",
                        "~/Scripts/angular-ui/ui-bootstrap-tpls.min.js",
                        "~/Scripts/angular-ui/ui-utils.min.js",
                        "~/Scripts/ui-grid.js",
                        "~/Scripts/underscore.min.js",
                        "~/Scripts/angular-local-storage.min.js",
                        "~/Scripts/others/dashboard/dist/angular-dashboard-framework.min.js",

**Comment by scorchloh** [comment]
I was having the same issue. Downgrading angular-ui-sortable to version 0.13.0 solved it for me.

**Comment by ebtc** [comment]
@scorchloh thanks, that does indeed solve the issue. I also see that Sebastian has changed the bower dependency for this.

**Comment by mingledj** [comment]
That indeed fixed the issue! Thank you very much!

**Comment by w3media** [comment]
Hi

We are having the same issue. Downgrading "angular-ui-sortable " did not work.

We use Yeoman Angular Gulp generator. At the beginning it worked fine. But after i commit the project to github, and Pull it to another computer. It give that error. So its still working on my master computer but not the other systems

Bower.json

{
  "name": "startertokenBasedApi",
  "version": "0.0.0",
  "dependencies": {
    "angular-animate": "~1.3.4",
    "angular-sanitize": "~1.3.4",
    "jquery": "~2.1.1",
    "restangular": "~1.4.0",
    "angular-ui-router": "~0.2.13",
    "bootstrap": "~3.3.1",
    "angular-bootstrap": "~0.12.0",
    "angular": "~1.3.4",
    "angular-ui-sortable": "~0.13.3",
    "jquery-ui": "~1.11.4",
    "angular-local-storage": "~0.1.5",
    "highcharts": "~4.1.4",
    "highcharts-ng": "~0.0.8",
    "angular-google-chart": "~0.0.11",
    "ng-table": "~0.5.4",
    "angular-breadcrumb": "~0.3.3"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.4"
  },
  "resolutions": {
    "jquery": "~2.1.1",
    "angular": "~1.3.4"
  }
}


index. html

 
    
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="../bower_components/angular/angular.js"></script>
    <script src="../bower_components/angular-animate/angular-animate.js"></script>
    <script src="../bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="../bower_components/lodash/dist/lodash.compat.js"></script>
    <script src="../bower_components/restangular/dist/restangular.js"></script>
    <script src="../bower_components/angular-ui-router/release/angular-ui-router.js"></script>
    <script src="../bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="../bower_components/jquery-ui/jquery-ui.js"></script>
    <script src="../bower_components/angular-ui-sortable/sortable.js"></script>
    <script src="../bower_components/angular-local-storage/dist/angular-local-storage.js"></script>
    <script src="../bower_components/highcharts/highcharts.js"></script>
    <script src="../bower_components/highcharts/highcharts-more.js"></script>
    <script src="../bower_components/highcharts/modules/exporting.js"></script>
    <script src="../bower_components/highcharts-ng/dist/highcharts-ng.js"></script>
    <script src="../bower_components/angular-google-chart/ng-google-chart.js"></script>
    <script src="../bower_components/ng-table/dist/ng-table.min.js"></script>
    <script src="../bower_components/angular-breadcrumb/release/angular-breadcrumb.js"></script>
    
    

    
    
    <script src="app/widgets/dataTable/helpers/config/ConfigEditor.js"></script>
    <script src="app/widgets/SimpleDataLoader/DataSet/dataSet.js"></script>
    <script src="components/showdown/src/showdown.js"></script>
    <script src="app/widgets/weather/weather.js"></script>
    <script src="app/widgets/randommsg/randommsg.js"></script>
    <script src="app/widgets/version/version.js"></script>
    <script src="app/widgets/news/news.js"></script>
    <script src="app/widgets/markdown/markdown.js"></script>
    <script src="app/widgets/github/github.js"></script>
    <script src="app/widgets/linklist/linklist.js"></script>
    <script src="app/widgets/gchart/gcharts.js"></script>
    <script src="app/widgets/dataTable/dataTable.js"></script>
    <script src="app/angular-dashboard-framework/scripts/adf.js"></script>
    <script src="app/angular-dashboard-framework/scripts/widget.js"></script>
    <script src="app/angular-dashboard-framework/scripts/widget-content.js"></script>
    <script src="app/angular-dashboard-framework/scripts/row.js"></script>
    <script src="app/angular-dashboard-framework/scripts/provider.js"></script>
    <script src="app/angular-dashboard-framework/scripts/dashboard.js"></script>
    <script src="app/angular-dashboard-framework/scripts/column.js"></script>

**Comment by scorchloh** [comment]
Hello.

Your bower.json specifies version 0.13.3 for angular-ui-sortable. Only version 0.13.0 worked for me.
You can also try updating angular-dashboard-framework to version 0.8.0 which uses Sortable instead of angular-ui-sortable.

**Comment by w3media** [comment]
Thanks a lot. It Worked!
