### ISSUE TITLE
TypeError: Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by magno32** [sdorra/angular-dashboard-framework#81]
I looked at the fix for #73, but am getting the same error below. 

TypeError: Cannot read property 'unshift' of undefined
    at Scope.controller.$scope.addWidgetDialog.addScope.addWidget [as addWidget]

![err](https://cloud.githubusercontent.com/assets/1031187/7071281/0a88940a-deaa-11e4-8ade-77be62d1e189.png)

**Comment by sdorra** [comment]
I've created a more robust method to add new widgets to the model. But could you post the structure you used?

**Comment by magno32** [comment]
I used the line from the [getting started] (https://github.com/sdorra/angular-dashboard-framework/wiki/Getting-started#add-the-dashboard-to-your-page)  page.  I'm just trying to start using adf, so I guess you mean the "6-6" in:
```xml
<adf-dashboard name="homeDashboard" collapsible="false" structure="6-6" adf-model="model"  />
```

**Comment by sdorra** [comment]
Sorry, but i'm not able to reproduce this problem. It is possible that you post a sample project?

**Comment by magno32** [comment]
I updated my dependency with your changes,  and the problem went away
