### ISSUE TITLE
Saving current state of the dashboard

### ISSUE THREAD

**Issue by ackuser** [sdorra/angular-dashboard-framework#83]
Is there a way to save/persist the current state of the dashboard on a DB or something like that?

**Comment by sdorra** [comment]
You can use the adfDashboardChanged event to store the dashboard model:

```javascript
$scope.$on('adfDashboardChanged', function(event, name, model) {
  storeService.set(name, model);
});
```

Please have a look at the [adf-dynamic-example](https://github.com/sdorra/adf-dynamic-example/blob/master/public/scripts/app.js) for a real world example.

**Comment by ackuser** [comment]
Thanks, I appreciate it. I will have a look.
