### ISSUE TITLE
Grunt minify of adf with other libs into a single js file throws 'Uknown provider error' on 'adf-widget-content' directive

### ISSUE THREAD

**Issue by thefitzpaddy** [sdorra/angular-dashboard-framework#84]
I have included adf into my web app as a bower dependency. In the unminified version of the app, where each library is included individually in the index.html, 'angular-dashboard-framework.min.js' works as expected.

When I run grunt build to minify all my project dependencies into the 'dist' folder, I receive the following error when loading my angular-dashboard-framework;

    Error: [$injector:unpr] Unknown provider: aProvider <- a
        http://errors.angularjs.org/1.3.13/$injector/unpr?p0=aProvider%20%3C-%20a
        at http://localhost:8181/scripts/vendor.4000d387.js:4:19007
        at http://localhost:8181/scripts/vendor.4000d387.js:5:4912
        at Object.d [as get] (http://localhost:8181/scripts/vendor.4000d387.js:5:4082)
        at http://localhost:8181/scripts/vendor.4000d387.js:5:5009
        at d (http://localhost:8181/scripts/vendor.4000d387.js:5:4082)
        at Object.e [as invoke] (http://localhost:8181/scripts/vendor.4000d387.js:5:4419)
        at http://localhost:8181/scripts/vendor.4000d387.js:26:9095
        at Object.f [as forEach] (http://localhost:8181/scripts/vendor.4000d387.js:4:19498)
        at l (http://localhost:8181/scripts/vendor.4000d387.js:26:9027)
        at link (http://localhost:8181/scripts/vendor.4000d387.js:26:9566) <adf-widget-content model="definition" content="widget" class="ng-isolate-scope"

**Comment by pihomeserver** [comment]
Same issue here. I use a fork of version 0.7.0.

I tried to replace with the latest version (that uses gulp) and still have the same error in the client

**Comment by sdorra** [comment]
@pihomeserver do you have widgets in your build? I ask because the sample widget source files, are not annotated until now.

**Comment by pihomeserver** [comment]
@sdorra : no widgets. I forked your 0.7.0 to change some parts of the main layout and widgets templates (not widgets them self). Then i build using the grunt build command.

For now the only way i found to use your framework (in a production build) is to move the subfolder that contains minified files outside of the folders minified by grunt.

**Comment by thefitzpaddy** [comment]
This issue has been solved by setting the `mangle` option of **Grunt** `uglify` to false

    ....
    uglify: {
      options: {
            mangle: false
        }
    .....
