### ISSUE TITLE
"Singleton"-Widgets

### ISSUE THREAD

**Issue by lukee910** [sdorra/angular-dashboard-framework#85]
Would it be possible to create Widgets that only can be put on the Dashboard once? Or is that not in the sense of Widgets?

**Comment by sdorra** [comment]
This is not possible at the moment, but i will keep this is mind.

**Comment by lukee910** [comment]
```
if (angular.isFunction(widgetFilter)){
  widgets = {};
  angular.forEach(dashboard.widgets, function(widget, type){
    if (widgetFilter(widget, type)){
      widgets[type] = widget;
    }
  });
} else {
  widgets = dashboard.widgets;
}
```
This code is at line 442 of angular-dashboard-framework.js. It fills the object `widgets` that is used in the `addWidgetDialog`, you'll be able to add every widget that is in that object. 

Is there a way to set the `widgetFilter` function to check if it is in the model? This is in the `adfDashboard` directive, where you have access to the model.

**Comment by sdorra** [comment]
The widget filter get now the model as third parameter. You should now be able to search, if a widget already exists in the model.

**Comment by lukee910** [comment]
Thanks a lot.
