### ISSUE TITLE
One Controller for Widget-Edit-Template

### ISSUE THREAD

**Issue by ToKaDev** [sdorra/angular-dashboard-framework#86]
Hi, can i use one controller for my Widget-Edit template which is used in multiple widgets?

**Comment by sdorra** [comment]
Yes, this should be possible with the help of angular modules. You have to define a module "A" which defines the controller, after that you can configure multiple modules which depend on module "A". The depending modules should be able to use the controller:

```javascript
angular.module('a', [])
  .controller('widgetController', function(){
    // do something
  });

angular.module('b', ['a', 'adf.provider'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('aw', {
        title: 'Awesome widget',
        description: 'My awesome widget',
        templateUrl: 'src/view.html',
        edit: {
          controller: 'widgetController',
          templateUrl: 'src/edit.html'
        }
  })
```
