### ISSUE TITLE
How to access widget data from postLink function in widget.js

### ISSUE THREAD

**Issue by ToKaDev** [sdorra/angular-dashboard-framework#88]
Hi, 
is it possible to access widget data (resolves) from postLink function in widget.js?
Greetings

**Comment by sdorra** [comment]
Yes, the widget object is in the scope:

```javascript
var widget = $scope.widget;
var resolve = widget.resolve;
```

But why you need this?

**Comment by ToKaDev** [comment]
Because i want to add a new icon to my widgets header (additional to refresh / move / close ...) that starts a export from the data shown in the widget. So i need to access the widget data in the onclick method declared in the postLink function.
