### ISSUE TITLE
Modal will not close when using angular-dashboard-framework with UI Bootstrap 0.13.0 

### ISSUE THREAD

**Issue by c5racing** [sdorra/angular-dashboard-framework#96]
We tried to upgrade to UI Bootstrap 0.13.0 and now the adf modal will not close.  We use UI Bootstrap modals throughout our application and do not have any issues.  Anyone else experiencing this?

**Comment by cleon26** [comment]
We have recently upgraded and experience the same problem.  Did you find a fix for this?

**Comment by sdorra** [comment]
Their is no fix at the moment, but their is a discussion at #91

**Comment by cleon26** [comment]
I have removed some parts (it seems to be related to animations) of ui-bootstrap-tpls.js temporarily so at least my qa team can close these dialogs for now.  Thanks in advance for working on the fix.
