### ISSUE TITLE
How to implement a cancel button?

### ISSUE THREAD

**Issue by miguelrincon** [sdorra/angular-dashboard-framework#97]
I am trying to extend the default function of ADF to include a cancel button in the edit widget popup.

Maybe I am misusing some part of the framework, but I don't know how could I implement cancel option. In the widget.html I found closeDialog.
```
ng-click="closeDialog()"
```
But I found no other options to "cancel"

Note: In my application I edit the templates directory with my own to be able to change the popup html by changing the value:

```javascript
.value('adfTemplatePath', 'src/shared/templates/adf/')
```

Note 2: I only change my model on $destroy, in my edit controller, as I don't want to update the config every time the user makes a change:
```javascript
$scope.$on('$destroy', function() {
  $scope.config.params = $scope.newParams;
}
```

**Comment by sdorra** [comment]
Fixed by #127
