### ISSUE TITLE
Store Dashboard on Server

### ISSUE THREAD

**Issue by bgruenefeld** [sdorra/angular-dashboard-framework#98]
Hi,

dashboard is actually stored in the localstorage of the browser.
Is it possible to store the dashboard on the server side?
If it is possible could you please give me a hint how to extend the framework

thanks in advance
Bernd

**Comment by sdorra** [comment]
Please have a look at the [adf-dynamic-example](https://github.com/sdorra/adf-dynamic-example). The project uses the adfDashboardChanged event to store the dashboard model via a node.js express rest api.
